# Generated by Django 3.2.16 on 2022-11-23 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('reg_number', models.CharField(max_length=255)),
                ('passcode', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
            ],
        ),
    ]
