# Generated by Django 3.2.16 on 2022-12-12 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Spaces',
            new_name='Space',
        ),
    ]
