# Generated by Django 3.2.16 on 2022-12-12 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0004_rename_spaces_rooms'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Rooms',
            new_name='Spaces',
        ),
        migrations.DeleteModel(
            name='Space',
        ),
    ]
