# Generated by Django 3.2.16 on 2022-12-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0006_rooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaces',
            name='status',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
