# Generated by Django 3.2.16 on 2022-12-12 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hostel', '0007_spaces_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaces',
            name='status',
            field=models.IntegerField(null=True),
        ),
    ]
